### ISSUE TITLE
Trekkie Bot

### ISSUE THREAD

**Issue by owocki** [gitcoinco/kudosbadges#157]
# Timeline

# Title

Trekkie Bot

# Design Inspiration

[star trek original](https://www.google.com/search?biw=960&bih=946&tbm=isch&sa=1&ei=4lNgXM-oIKiI0wLIg6_oAg&q=star+trek+original&oq=star+trek+original&gs_l=img.3..0l10.1649.2138..2297...0.0..0.95.688.8......1....1..gws-wiz-img.phoQhZ1QjYI) combined with 
and [gitcoin robots](https://github.com/gitcoinco/creative/tree/master/Marketing/Art/Robots) too

# Metadata

```
- name: 
  description: 
  priceFinney: 
  numClonesAllowed: 
  to_address: 
  tags: 
   - tag1
   - tag2
```

# Down Payment

# Gen0 Owner Address
