### ISSUE TITLE
Moloch

### ISSUE THREAD

**Issue by owocki** [gitcoinco/kudosbadges#158]
# Timeline

Moloch

# Title

Moloch

# Design Inspiration

https://www.google.com/search?q=moloch&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjSkpKQy7LgAhX7IjQIHU2MDOAQ_AUIDigB&biw=1280&bih=698#imgrc=nqRzz5YcBud8kM:

# Metadata

```
- name: 
  description: 
  priceFinney: 
  numClonesAllowed: 
  to_address: 
  tags: 
   - tag1
   - tag2
```

# Down Payment

# Gen0 Owner Address
