### ISSUE TITLE
The Joe-ker

### ISSUE THREAD

**Issue by owocki** [gitcoinco/kudosbadges#159]
# Timeline

# Title

The Joe-ker

# Design Inspiration

https://i0.wp.com/img09.deviantart.net/7340/i/2015/106/9/a/joker_card___harley_quinn_cosplay__injustice__by_sylunahirokashi-d7szxun.jpg
but please make the face [joe lubin](https://www.google.com/search?q=joe+lubin&tbm=isch&source=iu&ictx=1&fir=L5VUZUujJ1IWAM%253A%252CenXglIfq_TbhPM%252C%252Fg%252F11c6ccht_w&usg=AI4_-kRlWn5cY7h9GygOGk6A64nDfEnJsg&sa=X&ved=2ahUKEwiU_fWl-7ngAhWymeAKHUh6CIsQ_B0wD3oECAQQBg#imgrc=L5VUZUujJ1IWAM:) and way less scary looking.  he should look friendly!

# Metadata

```
- name: 
  description: 
  priceFinney: 
  numClonesAllowed: 
  to_address: 
  tags: 
   - tag1
   - tag2
```

# Down Payment

# Gen0 Owner Address
