### ISSUE TITLE
blue spikey shell

### ISSUE THREAD

**Issue by owocki** [gitcoinco/kudosbadges#166]
# Timeline

# Title

blue spikey shell

# Design Inspiration

https://www.google.com/search?q=blue+spiny+shell&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjDxdGD_cjgAhUlpIMKHRKAD40Q_AUIDygC&biw=1440&bih=680

# Metadata

```
- name: 
  description: 
  priceFinney: 
  numClonesAllowed: 
  to_address: 
  tags: 
   - tag1
   - tag2
```

# Down Payment

# Gen0 Owner Address
