### ISSUE TITLE
Gitcoin Torchbearer

### ISSUE THREAD

**Issue by willsputra** [gitcoinco/kudosbadges#171]
# Timeline
# Title
Gitcoin Torchbearer

# Design Inspiration
[Olympic torchbearer
](https://www.google.com/search?q=olympic+torchbearer&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiYt5_hvdfgAhXQdn0KHdVxCOYQ_AUIDigB&biw=1680&bih=948&dpr=2
)
# Metadata
```
- name: 
  description: 
  priceFinney: 
  numClonesAllowed: 
  to_address: 
  tags: 
   - tag1
   - tag2
```
# Down Payment
# Gen0 Owner Address
