### ISSUE TITLE
go go power rangers

### ISSUE THREAD

**Issue by owocki** [gitcoinco/kudosbadges#176]
# Timeline

# Title

go go power rangers

# Design Inspiration

https://static3.srcdn.com/wordpress/wp-content/uploads/Power-Rangers-Alpha-Zords1.jpg

# Metadata

```
- name: 
  description: 
  priceFinney: 
  numClonesAllowed: 
  to_address: 
  tags: 
   - tag1
   - tag2
```

# Down Payment

# Gen0 Owner Address
