### ISSUE TITLE
shepherd

### ISSUE THREAD

**Issue by owocki** [gitcoinco/kudosbadges#183]
# Timeline

# Title

shepherd

# Design Inspiration

http://2.bp.blogspot.com/_RgQ_XUDZTyM/SxW0zCuStNI/AAAAAAAACzc/QmMdB3Tr-8Q/s1600/Shephrd1.gif

# Metadata

```
- name: 
  description: 
  priceFinney: 
  numClonesAllowed: 
  to_address: 
  tags: 
   - tag1
   - tag2
```

# Down Payment

# Gen0 Owner Address
