### ISSUE TITLE
woke-est

### ISSUE THREAD

**Issue by owocki** [gitcoinco/kudosbadges#184]
# Timeline

# Title

woke-est

# Design Inspiration

https://punchdrink.com/articles/wine-world-unwoke-food-media-anthony-bourdain/
(but the person in the sunglasses refletion should NOT be drinking wine)

# Metadata

```
- name: 
  description: 
  priceFinney: 
  numClonesAllowed: 
  to_address: 
  tags: 
   - tag1
   - tag2
```

# Down Payment

# Gen0 Owner Address
