### ISSUE TITLE
Junior release manager

### ISSUE THREAD

**Issue by owocki** [gitcoinco/kudosbadges#185]
# Timeline

# Title

Junior release manager

# Design Inspiration

https://www.google.com/search?biw=960&bih=946&tbm=isch&sa=1&ei=kJeAXNaKO-fjjwSn4r2oCA&q=junior+ranger+badge&oq=junior+ranger+badge&gs_l=img.3...0.0..15636...0.0..0.0.0.......1......gws-wiz-img.ftyuj8jaKKM

# Metadata

```
- name: 
  description: 
  priceFinney: 
  numClonesAllowed: 
  to_address: 
  tags: 
   - tag1
   - tag2
```

# Down Payment

# Gen0 Owner Address
