### ISSUE TITLE
Sultan of shill

### ISSUE THREAD

**Issue by owocki** [gitcoinco/kudosbadges#186]
# Timeline

# Title

Sultan of shill

# Design Inspiration

https://www.google.com/search?biw=960&bih=946&tbm=isch&sa=1&ei=speAXNP8CqHcjwSMq5-4DA&q=sultan+disney&oq=sultan+disney&gs_l=img.3..0j0i8i30l2j0i5i30j0i24l2.4609.5192..5305...0.0..0.67.383.7......1....1..gws-wiz-img.......0i67j0i30.1Wn2jKd6gIQ

# Metadata

```
- name: 
  description: 
  priceFinney: 
  numClonesAllowed: 
  to_address: 
  tags: 
   - tag1
   - tag2
```

# Down Payment

# Gen0 Owner Address
