### ISSUE TITLE
youre a star

### ISSUE THREAD

**Issue by owocki** [gitcoinco/kudosbadges#189]
# Timeline

# Title

youre a star

# Design Inspiration

http://bits.owocki.com/375149d75815/Screen%20Shot%202019-03-07%20at%209.20.58%20AM.png
but test should say 'youre a star!'

# Metadata

```
- name: 
  description: 
  priceFinney: 
  numClonesAllowed: 
  to_address: 
  tags: 
   - tag1
   - tag2
```

# Down Payment

# Gen0 Owner Address
