### ISSUE TITLE
Code Eating HIppo

### ISSUE THREAD

**Issue by wanseob** [gitcoinco/kudosbadges#190]
# Timeline
The sooner the better. We hold "Comuka" event every Saturday. It is kind of a Saturday coding salon(https://comuka.nonce.community) or a weekly casual hackathon. We have a plan to send Kudos to the participants every week. 

# Title
Code Eating Hippo

# Design Inspiration

Profile image of https://twitter.com/CodeEatingHippo
![](https://pbs.twimg.com/profile_images/1098615185835646976/7CExeYoZ_400x400.png)

# Metadata

```
- name: Code Eating Hippo
  description: Comuka is a code-eating hippo living in nonce community. Hang out and code together every Saturday with Comuka.
  priceFinney: 1
  numClonesAllowed: 1000
  to_address: 0x5dD03D36358d6Da50D758F2EF6e18423F6CF42C4
  tags: 
   - Saturday Coding Salon
   - Weekly casual hackathon
```

# Down Payment

https://etherscan.io/tx/0x66b46518e4316a7b969992c95e527d1b4197ec8a329d3a837e571a3089a430f9

# Gen0 Owner Address

0x5dD03D36358d6Da50D758F2EF6e18423F6CF42C4
