### ISSUE TITLE
ENS Kudos

### ISSUE THREAD

**Issue by Arachnid** [gitcoinco/kudosbadges#193]
# Timeline

Before EDCon (8 April) would be ideal.

# Title

ENS Enabled

# Design Inspiration

ENS Identity: https://drive.google.com/file/d/1kojIkm4K4d4v1ozxvg8AzZa7MLk7rRdV/view?usp=sharing

# Metadata

```
- name: ENS Enabled
  description: You set yourself up with an ENS name!
  priceFinney: 10
  numClonesAllowed: 1000
  to_address: 0x911143d946ba5d467bfc476491fdb235fef4d667
  tags: 
   - ENS
   - Naming
```

# Down Payment

https://etherscan.io/tx/0x402d92c5cda09481e9eef5183c71b46c5f0de283ae249dbdb0eff55c1730f40f

# Gen0 Owner Address

0xfdb33f8ac7ce72d7d4795dd8610e323b4c122fbb
