### ISSUE TITLE
BDFL

### ISSUE THREAD

**Issue by owocki** [gitcoinco/kudosbadges#194]
# Timeline

# Title

BDFL (benevolent dictator for life)

# Design Inspiration

https://www.google.com/search?q=dictator&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjvw82WqYrhAhVs9YMKHacTAzwQ_AUIDigB&biw=1440&bih=647#imgrc=_

but please make the dictator "shine" and glow a little bit.  he is benevolent after all

# Metadata

```
- name: 
  description: 
  priceFinney: 
  numClonesAllowed: 
  to_address: 
  tags: 
   - tag1
   - tag2
```

# Down Payment

# Gen0 Owner Address
