### ISSUE TITLE
i want you to BUIDL on ETH

### ISSUE THREAD

**Issue by owocki** [gitcoinco/kudosbadges#195]
# Timeline

# Title

I want you to BUIDL on ETH

# Design Inspiration

https://www.google.com/search?q=i+want+you+poster&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiL4JXkrYrhAhWO8oMKHY52D18Q_AUIDigB&biw=1440&bih=682

# Metadata

```
- name: 
  description: 
  priceFinney: 
  numClonesAllowed: 
  to_address: 
  tags: 
   - tag1
   - tag2
```

# Down Payment

# Gen0 Owner Address
