### ISSUE TITLE
saved by the bell

### ISSUE THREAD

**Issue by owocki** [gitcoinco/kudosbadges#196]
# Timeline

# Title

saved by the bell

# Design Inspiration

https://www.google.com/search?biw=1920&bih=897&tbm=isch&sa=1&ei=jgmPXIyHN5-jjwTNoI6oAw&q=saved+by+the+bell+logo&oq=saved+by+the+bell+logo&gs_l=img.3..0l8.1935.2292..2452...0.0..0.85.141.2......1....1..gws-wiz-img.78fgrdqS-0E#imgrc=KGwNuRuuKncVDM:

# Metadata

```
- name: 
  description: 
  priceFinney: 
  numClonesAllowed: 
  to_address: 
  tags: 
   - tag1
   - tag2
```

# Down Payment

# Gen0 Owner Address
