### ISSUE TITLE
holy hand grenade

### ISSUE THREAD

**Issue by owocki** [gitcoinco/kudosbadges#200]
# Timeline

# Title

holy hand grenade

# Design Inspiration

https://www.google.com/search?q=holy+hand+grenade&source=lnms&tbm=isch&sa=X&ved=0ahUKEwinlcGP6pPhAhUHh-AKHaBzB8gQ_AUIDigB&biw=2560&bih=1257

# Metadata

```
- name: 
  description: 
  priceFinney: 
  numClonesAllowed: 
  to_address: 
  tags: 
   - tag1
   - tag2
```

# Down Payment

# Gen0 Owner Address
