### ISSUE TITLE
hackathon judges

### ISSUE THREAD

**Issue by owocki** [gitcoinco/kudosbadges#201]
# Timeline

# Title

hackathon judge

# Design Inspiration

https://www.google.com/search?q=judge&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjP0LSZ9JPhAhWKiOAKHfKWBQwQ_AUIDigB&biw=1280&bih=1306

# Metadata

```
- name: 
  description: 
  priceFinney: 
  numClonesAllowed: 
  to_address: 
  tags: 
   - tag1
   - tag2
```

# Down Payment

# Gen0 Owner Address
