### ISSUE TITLE
clippy ship it

### ISSUE THREAD

**Issue by owocki** [gitcoinco/kudosbadges#203]
# Timeline

# Title

# Design Inspiration

http://bits.owocki.com/72ef613988e2/Clippy_ShipIt.gif

# Metadata

```
- name: 
  description: 
  priceFinney: 
  numClonesAllowed: 
  to_address: 
  tags: 
   - tag1
   - tag2
```

# Down Payment

# Gen0 Owner Address
