### ISSUE TITLE
doge

### ISSUE THREAD

**Issue by owocki** [gitcoinco/kudosbadges#204]
# Timeline

# Title

doge

# Design Inspiration

https://www.google.com/search?q=doge&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjIq7L_r53hAhVwIDQIHcpLAaIQ_AUIDigB&biw=2560&bih=1306

# Metadata

```
- name: 
  description: 
  priceFinney: 
  numClonesAllowed: 
  to_address: 
  tags: 
   - tag1
   - tag2
```

# Down Payment

# Gen0 Owner Address
