### ISSUE TITLE
jon snow

### ISSUE THREAD

**Issue by owocki** [gitcoinco/kudosbadges#209]
# Timeline

# Title

jon snow

# Design Inspiration

# Metadata

```
- name: 
  description: 
  priceFinney: 
  numClonesAllowed: 
  to_address: 
  tags: 
   - tag1
   - tag2
```

# Down Payment

# Gen0 Owner Address
