### ISSUE TITLE
MetaMask Fam kudo

### ISSUE THREAD

**Issue by bdresser** [gitcoinco/kudosbadges#214]
# Timeline
would love this in a week or two -- we've started the MetaMask mobile private beta and want to incentivize more folks to give feedback! (@vs77bb @owocki )

# Title
IDK what do you think!!!!
* MetaMask Fam
* Helper Fox
* Detective Fox? 

# Design Inspiration
misc brand inspo [here](https://docs.google.com/presentation/d/11eT7Y1DEdXuMSqSZ5h0S4pwEWtr43iMKZUjmzx1dCYM/edit#slide=id.g3d12ab5418_1_139)

# Metadata

```
- name: Helper Fox
  description: You are a cherished member of the MetaMask community. Thanks for helping!
  priceFinney: 
  numClonesAllowed: 500
  to_address: `0x12c8ff915ad423cfA1c03E6D0749F1eBAc582959` assuming this is where they should be sent once minted? 
  tags: ethereum, metamask, community, bugs, mobile
```

# Down Payment
[link](https://etherscan.io/tx/0x58e4cf48303f26699333d156d10d0cbb36ba33b926918ed3aa6ad18857317d2c)

# Gen0 Owner Address
0x8775A0489bd87c40cd40807B6A9eED145aB84E03
