### ISSUE TITLE
oracle

### ISSUE THREAD

**Issue by owocki** [gitcoinco/kudosbadges#218]
# Timeline

# Title

oracle

# Design Inspiration

https://www.google.com/search?biw=1920&bih=946&tbm=isch&sa=1&ei=8qeqXNLQOcec5gK9pig&q=all+seeing+oracle&oq=all+seeing+oracle&gs_l=img.3..0i24.8253.9547..9635...0.0..0.89.1317.16......1....1..gws-wiz-img.......0j0i67j0i8i30.sukRBX9VWc4#imgrc=nPQV3bTQcUJNuM:

# Metadata

```
- name: 
  description: 
  priceFinney: 
  numClonesAllowed: 
  to_address: 
  tags: 
   - tag1
   - tag2
```

# Down Payment

# Gen0 Owner Address
