### ISSUE TITLE
Meme warrior

### ISSUE THREAD

**Issue by owocki** [gitcoinco/kudosbadges#228]
# Timeline

# Title

Meme warrior

# Design Inspiration

https://www.google.com/search?biw=1440&bih=689&tbm=isch&sa=1&ei=V-qzXMCrGMjksAWH9pS4CA&q=mechwarrior+cover&oq=mechwarrior+cover&gs_l=img.3...4526.4914..5008...0.0..0.73.391.6......1....1..gws-wiz-img.......0i67j0.kFq7HPTmDtA

# Metadata

```
- name: 
  description: 
  priceFinney: 
  numClonesAllowed: 
  to_address: 
  tags: 
   - tag1
   - tag2
```

# Down Payment

# Gen0 Owner Address
