### ISSUE TITLE
sneaky

### ISSUE THREAD

**Issue by owocki** [gitcoinco/kudosbadges#229]
# Timeline

# Title

sneakey

# Design Inspiration

https://nofilmschool.com/sites/default/files/styles/article_wide/public/raiders1.jpg?itok=eqKAZwDZ

# Metadata

```
- name: 
  description: 
  priceFinney: 
  numClonesAllowed: 
  to_address: 
  tags: 
   - tag1
   - tag2
```

# Down Payment

# Gen0 Owner Address
