### ISSUE TITLE
webmaster

### ISSUE THREAD

**Issue by owocki** [gitcoinco/kudosbadges#232]
# Timeline

# Title

webmaster

# Design Inspiration

https://www.google.com/search?biw=1440&bih=637&tbm=isch&sa=1&ei=J5y3XOz9E4fYwALSqYWoDQ&q=webmaster+nerd&oq=webmaster+nerd&gs_l=img.3...11102.11612..11712...0.0..0.61.294.5......1....1..gws-wiz-img.......0j0i67j0i30j0i24.RQVR_dNfumo
# Metadata

```
- name: 
  description: 
  priceFinney: 
  numClonesAllowed: 
  to_address: 
  tags: 
   - tag1
   - tag2
```

# Down Payment

# Gen0 Owner Address
