### ISSUE TITLE
Da Vinci

### ISSUE THREAD

**Issue by vs77bb** [gitcoinco/kudosbadges#236]
# Timeline

# Title

# Design Inspiration

https://www.google.com/search?q=da+vinci&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjgwKuIgOnhAhXmY98KHUAtC2oQ_AUIDigB&biw=1437&bih=726#imgrc=Gd89g1u2kt7sNM:

# Metadata

```
- name: 
  description: 
  artist: 
  priceFinney: 
  numClonesAllowed: 
  to_address: 
  can_be_sent_by: 
  marketplace_listed: True
  tags: 
   - tag1
   - tag2
```

# Down Payment

# Gen0 Owner Address
