### ISSUE TITLE
Michelangelo

### ISSUE THREAD

**Issue by vs77bb** [gitcoinco/kudosbadges#237]
# Timeline

# Title

# Design Inspiration

![image](https://user-images.githubusercontent.com/23297747/56670539-01e35200-6681-11e9-9e65-1fc2792bf284.png)

# Metadata

```
- name: Michelangelo's David
  description: A representation of strength of the individual human to chart their own course.  
  artist: 
  priceFinney: 
  numClonesAllowed: 5
  to_address: 
  can_be_sent_by: 
  marketplace_listed: True
  tags: 
   - tag1
   - tag2
```

# Down Payment

# Gen0 Owner Address
