### ISSUE TITLE
Tim Berners Lee

### ISSUE THREAD

**Issue by vs77bb** [gitcoinco/kudosbadges#238]
# Timeline

# Title

# Design Inspiration

![image](https://user-images.githubusercontent.com/23297747/56671055-ea589900-6681-11e9-809b-f8d0b06aebb5.png)

# Metadata

```
- name: 
  description: For those carrying on the legacy of TBL, building the protocols of the future. 
  artist: 
  priceFinney: 
  numClonesAllowed: 100
  to_address: 
  can_be_sent_by: 
  marketplace_listed: True
  tags: 
   - tag1
   - tag2
```

# Down Payment

# Gen0 Owner Address
