### ISSUE TITLE
Application Alliance

### ISSUE THREAD

**Issue by owocki** [gitcoinco/kudosbadges#242]
# Timeline

# Title

Application Alliance

# Design Inspiration

Please feel free to reuse this asset for this logo
https://gitcoin.co/kudos/430/resilience

The design should
* any color
* should have the words "Application Alliance" on it
* should have 3 shields. [inspiration](https://www.google.com/search?biw=1920&bih=946&tbm=isch&sa=1&ei=vQjPXJq2GIWGsQWm8YGYDw&q=shield+alliance&oq=shield+alliance&gs_l=img.3..0i8i30l3j0i24.504.504..685...0.0..0.94.94.1......0....1..gws-wiz-img.41JvLJrrMPw)

# Metadata

```
- name: 
  description: 
  artist: 
  priceFinney: 
  numClonesAllowed: 
  to_address: 
  can_be_sent_by: 
  marketplace_listed: True
  tags: 
   - tag1
   - tag2
```

# Down Payment

# Gen0 Owner Address
