### ISSUE TITLE
chicken wing

### ISSUE THREAD

**Issue by owocki** [gitcoinco/kudosbadges#243]
# Timeline

# Title

chicken wing

# Design Inspiration

https://www.google.com/search?q=chicken+wing&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjtj8uCpKPiAhVFM6wKHR2eC9cQ_AUIDigB&biw=960&bih=897

make it GLOW pls!

# Metadata

```
- name: 
  description: 
  artist: 
  priceFinney: 
  numClonesAllowed: 
  to_address: 
  can_be_sent_by: 
  marketplace_listed: True
  tags: 
   - tag1
   - tag2
```

# Down Payment

# Gen0 Owner Address
