### ISSUE TITLE
niger

### ISSUE THREAD

**Issue by junior221** [gitcoinco/kudosbadges#251]
# Timeline

# Title

# Design Inspiration

# Metadata

```
- name: 
  description: 
  artist: 
  priceFinney: 
  numClonesAllowed: 
  to_address: 
  can_be_sent_by: 
  marketplace_listed: True
  tags: 
   - tag1
   - tag2
```

# Down Payment

# Gen0 Owner Address
