### ISSUE TITLE
AdEx Kudos

### ISSUE THREAD

**Issue by vs77bb** [gitcoinco/kudosbadges#258]
# Timeline

# Title

AdEx Unicorn

# Design Inspiration

https://drive.google.com/drive/u/0/folders/1O2aUyHlqrKXN-v9u_h_HphqKejip_j7Q
![image](https://user-images.githubusercontent.com/23297747/62591239-f701a580-b89c-11e9-961a-4b9ec84bce50.png)

Unicorn from AdEex Website

# Metadata

```
- name: AdEx Unicorn
  description: A wonderful AdEx community member
  artist: mladen
  priceFinney: 1
  numClonesAllowed: 100
  to_address: 
  can_be_sent_by: 
  marketplace_listed: True
  tags: 
   - adex
   - community
   - growethereum
```

# Down Payment

# Gen0 Owner Address
