### ISSUE TITLE
bZx Kudos

### ISSUE THREAD

**Issue by vs77bb** [gitcoinco/kudosbadges#259]
# Timeline

Maybe by Monday, August 12th? Would like to get to sponsors by 8/14 latest.

# Title

# Design Inspiration

https://bzx.network/ (Website) 

![bzx](https://user-images.githubusercontent.com/23297747/62591513-ba827980-b89d-11e9-9e57-4253faeccac8.jpeg)

# Metadata

```
- name: bZx Trader
  description: For a bZx community member who has made meaningful contributions towards our decentralized trading future. 
  artist: mladen
  priceFinney: 1
  numClonesAllowed: 100
  to_address: 
  can_be_sent_by: 
  marketplace_listed: True
  tags: 
   - bzx
   - community
   - growethereum
```

# Down Payment

# Gen0 Owner Address
