### ISSUE TITLE
Fluence Kudos

### ISSUE THREAD

**Issue by vs77bb** [gitcoinco/kudosbadges#260]
# Timeline

Maybe by Monday, August 12th? Would like to get to sponsors by 8/14 latest. 

# Title

(In)Fluence(r)

# Design Inspiration

https://fluence.network/

![Blue logo](https://user-images.githubusercontent.com/23297747/62591856-04b82a80-b89f-11e9-96d9-a0b641cba697.png)

# Metadata

```
- name: (In)Fluence(r)
  description: Given for influential contributions to Fluence via code, community, or otherwise! 
  artist: mladen
  priceFinney: 1
  numClonesAllowed: 100
  to_address: 
  can_be_sent_by: 
  marketplace_listed: True
  tags: 
   - fluence
   - community
   - growethereum
```

# Down Payment

# Gen0 Owner Address
