### ISSUE TITLE
Mentor Kudos for ETHWaterloo

### ISSUE THREAD

**Issue by ChainSafeSystems** [gitcoinco/kudosbadges#267]
# Timeline

If possible we would love to have it for ETHWaterloo.

# Title

ETHWaterloo Mentor!

# Design Inspiration

Honestly the only thing that would be nice to have is a maple leaf =D

# Metadata

```
- name: 
  description: 
  artist: 
  priceFinney: 
  numClonesAllowed: 
  to_address: 
  can_be_sent_by: 
  marketplace_listed: True
  tags: 
   - tag1
   - tag2
```

# Down Payment

Will update this tomorrow! 

# Gen0 Owner Address

0x37b347ee521649b60275ba6fB63670fe7f77a0Fa
