### ISSUE TITLE
Algorand Kudos

### ISSUE THREAD

**Issue by connoroday** [gitcoinco/kudosbadges#268]
# Timeline

By Tuesday 10/1 would be ideal - 10/4 latest
# Title

Algorand - Road to Devcon

# Design Inspiration

https://res.cloudinary.com/startup-grind/image/upload/c_fill,f_auto,g_center,q_auto:good/v1/softlayer0/80135C1/media/v1/AUTH_d0619b05-07fc-49f0-8249-da585ea45ce5/algorand/contentbuilder/C_Algorand-Event-Thumbnail-400x400_EjNd7dj.png

https://icodrops.com/wp-content/uploads/2018/03/Algorand-banner-1.jpg

# Metadata

```
- name: Algorand - Road to Devcon
  description: Given for contributors to Algorand's Road to Devcon challenges 
  artist: mladen
  priceFinney: 1
  numClonesAllowed: 100
  to_address: 
  can_be_sent_by: 
  marketplace_listed: True
  tags: 
   - Road to Devcon
   - Algorand
   - Hackathon
```

# Down Payment

# Gen0 Owner Address
