### ISSUE TITLE
ConsenSys Grants Kudos

### ISSUE THREAD

**Issue by connoroday** [gitcoinco/kudosbadges#269]
# Timeline

By Tuesday 10/1 would be ideal - 10/4 latest
# Title

ConsenSys Grants - Road to Devcon

# Design Inspiration

https://miro.medium.com/max/8000/1*2f0rV3UDSCRW1s_x0siHxw.png

https://pages.consensys.net/hubfs/consensys-logo-blue-1.png

# Metadata

```
- name: Algorand - Road to Devcon
  description: Given for contributors to ConsenSys Grant's Road to Devcon challenges 
  artist: mladen
  priceFinney: 1
  numClonesAllowed: 100
  to_address: 
  can_be_sent_by: 
  marketplace_listed: True
  tags: 
   - Road to Devcon
   - ConsenSys Grants
   - Hackathon
   - Ethereum
```

# Down Payment

# Gen0 Owner Address
