### ISSUE TITLE
Road to Devcon Judges

### ISSUE THREAD

**Issue by connoroday** [gitcoinco/kudosbadges#270]
# Timeline

By Tuesday 10/1 would be ideal - 10/4 latest

# Title

Road to Devcon Judges

# Design Inspiration

Anything with the Road to Devcon logo with Judging imagery

http://bits.owocki.com/4c70cd6f6199/Screen%20Shot%202019-09-25%20at%2012.59.47%20PM.png

http://bits.owocki.com/603f937aacd1/Screen%20Shot%202019-09-25%20at%201.01.11%20PM.png

# Metadata

```
- name: Road to Devcon Judges
  description: Given for all judges contributing their time to The Road to Devcon hackathon
  artist: mladen
  priceFinney: 1
  numClonesAllowed: 100
  to_address: 
  can_be_sent_by: 
  marketplace_listed: True
  tags: 
   - Road to Devcon
   - Hackathon
   - Judges
   - Ethereum
```

# Down Payment

# Gen0 Owner Address
