### ISSUE TITLE
tirol

### ISSUE THREAD

**Issue by arminius3** [gitcoinco/kudosbadges#272]
![360px-Empress_Elisabeth_of_Austria_in_dancing-dress,_1865,_Franz_Xaver_Winterhalter](https://user-images.githubusercontent.com/56484910/68032374-dee3cb80-fcbd-11e9-9723-0cfda815541c.jpg)

# Timeline

# Title

# Design Inspiration

# Metadata

```
- name: 
  description: 
  artist: 
  priceFinney: 
  numClonesAllowed: 
  to_address: 
  can_be_sent_by: 
  marketplace_listed: True
  tags: 
   - tag1
   - tag2
```

# Down Payment

# Gen0 Owner Address
