### ISSUE TITLE
Meetup ETH Devs Sao Paulo

### ISSUE THREAD

**Issue by itsencrypted** [gitcoinco/kudosbadges#280]
# Timeline

# Title

# Design Inspiration: The Ethereum logo, but the main middle diamond with the middle diamond of the brazilian flag. 

# Metadata

```
- name: 
  description: 
  artist: 
  priceFinney: 
  numClonesAllowed: 
  to_address: 
  can_be_sent_by: 
  marketplace_listed: True
  tags: 
   - tag1
   - tag2
```

# Down Payment

# Gen0 Owner Address
