### ISSUE TITLE
blue steel

### ISSUE THREAD

**Issue by owocki** [gitcoinco/kudosbadges#281]
# Timeline

# Title

# Design Inspiration

https://www.google.com/search?q=blue+steel+zoolander&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjb7vGD5JnnAhUBwFkKHdHrCacQ_AUoAXoECAsQAw&biw=1645&bih=846#imgrc=k3eB7HztmrT1wM:

# Metadata

```
- name: 
  description: 
  artist: 
  priceFinney: 
  numClonesAllowed: 
  to_address: 
  can_be_sent_by: 
  marketplace_listed: True
  tags: 
   - tag1
   - tag2
```

# Down Payment

# Gen0 Owner Address
